# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: dbrest

before:
  hooks:
    - go mod edit -dropreplace='github.com/flarco/g' go.mod
    - go mod edit -dropreplace='github.com/slingdata-io/sling-cli' go.mod
    - go mod edit -droprequire='github.com/slingdata-io/sling' go.mod
    - go mod tidy

builds:
  - main: .
    
    env:
      - CGO_ENABLED=1

    goarch:
      - amd64
      # - '386'
      # - arm64
      # - arm
    # goarm:
    #   - '6'
    #   - '7'
    goos:
      - linux
    ldflags:
      - "-X 'github.com/dbrest-io/dbrest/state.Version={{ .Version }}' -X 'github.com/dbrest-io/dbrest/state.RudderstackURL={{ .Env.RUDDERSTACK_URL }}'"

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'

checksum:
  name_template: "{{ .ProjectName }}_{{ .Runtime.Goos }}_{{ .Runtime.Goarch }}_checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}"

dockers:
  - dockerfile: 'docker/Dockerfile'
    image_templates:
    - "dbrest/dbrest:latest"
    - "dbrest/dbrest:{{ .Tag }}"

release:
  mode: replace
  header: |
    ## dbREST {{ .Tag }} ({{ .Date }})

    